<a href="https://colab.research.google.com/github/Donmateo19/data-science_bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.19.5'

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'a

In [4]:
#help(np.array)
t=np.array([1, 3])
print(t)

[1 3]


In [5]:
t.ndim

1

In [6]:
type(t)

numpy.ndarray

In [7]:
t.shape

(2,)

In [8]:
t.size

2

In [9]:
t.dtype

dtype('int64')

2D array

In [10]:
x = np.array([[1,3],[2,4]])
x

array([[1, 3],
       [2, 4]])

In [11]:
x = np.array([[1,2,4],[4,3,1]])
print(x)

[[1 2 4]
 [4 3 1]]


3D ARRAY

In [12]:
import numpy as np
x = np.array(
    [[[4,3,1],
      [3,1,2]],

      [[4,1,3],
       [4,2,1]],
     [[5,6,7],
      [7,6,5]]]
    
)


In [13]:
x=np.zeros(shape=(4,10), dtype='int')
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [14]:
#help(np.full)
np.full(shape=(3,2),fill_value=17)

array([[17, 17],
       [17, 17],
       [17, 17]])

In [15]:
t= [val for val in range (0,10,2)]
t

[0, 2, 4, 6, 8]

In [16]:
np.arange(start = 10, stop = 100, step = 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)
A+B

[3 1 4 2]
[ 3 -1  3  2]


array([6, 0, 7, 4])

In [19]:
A-B

array([0, 2, 1, 0])

In [20]:
A*B

array([ 9, -1, 12,  4])

In [21]:
X = np.array ([[1,3], [-2,0]])
Y = np.array ([[6,0], [-1,2]])
print(X)
print(Y)


[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [22]:
X*Y
#mnozenie po elemencie - elementy na tych samych pozycjach są mnozenioen

array([[6, 0],
       [2, 0]])

In [23]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [24]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [25]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
np.random.randn(10,4)

In [33]:
print(round(np.random.rand(),3))

0.781


In [34]:
np.random.randint(low=10, high=101, size=5)

array([33, 24, 31, 30, 32])

In [38]:
x= [3,27,16,159]
np.random.choice(x)

159

In [40]:
data = np.arange(10)
data
np.random.shuffle(data)
data

array([5, 0, 1, 4, 2, 6, 8, 3, 7, 9])

In [41]:
np.exp(2)

7.38905609893065

In [43]:
np.all([2,3,1])

True

In [46]:
A = np.random.rand(5)
A

array([0.01703131, 0.33018341, 0.28208574, 0.81438947, 0.865548  ])

In [47]:
np.argmax(A)

4

In [49]:
A[np.argmax(A)]


array([0.01703131, 0.33018341, 0.28208574, 0.81438947, 0.865548  ])

In [74]:
B = [ 3, 4, 7 , 83]
print(np.mean(B))
print(np.max(B))
print(np.std(B))

24.25
83
33.9512518178638


In [72]:
A=np.arange(20)
A=A.reshape(4,5)
print(A[:,0])

print(A[0,2])

[ 0  5 10 15]
2


In [73]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [78]:
print(A)
for row in A:
  print(row[1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
1
6
11
16


In [79]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [80]:
B = A.T
print(B)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [97]:
A=np.arange(start = -10, stop = 10, step = 0.5)
A=A.reshape(10,-1)
#print(A)

A[np.bitwise_and(A>-5, A<5)]

print(A)

[[-10.   -9.5  -9.   -8.5]
 [ -8.   -7.5  -7.   -6.5]
 [ -6.   -5.5  -5.   -4.5]
 [ -4.   -3.5  -3.   -2.5]
 [ -2.   -1.5  -1.   -0.5]
 [  0.    0.5   1.    1.5]
 [  2.    2.5   3.    3.5]
 [  4.    4.5   5.    5.5]
 [  6.    6.5   7.    7.5]
 [  8.    8.5   9.    9.5]]
