<a href="https://colab.research.google.com/github/Donmateo19/data-science_bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
v1 = np.array([-1,4])
v1
np.linalg.norm(v1)

4.123105625617661

In [4]:
v2=np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

In [6]:
p = np.array([3,0])
q = np.array([0,4])
np.linalg.norm(q-p)

5.0

Odległość w 3D

In [7]:
p = np.array([3,0,1])
q = np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

mnozenie macierzy NIE JEST PRZEMIENNE


In [24]:
X = np.array([[5,3],[3,9]])
Y = np.array([[1],[-1]])
print(X, '\n')
print(Y,'\n')

print(np.dot(X,Y))
print(X.dot(Y))
Z = X@Y
print('n',Z)

print("to tyle ")
Z.shape

[[5 3]
 [3 9]] 

[[ 1]
 [-1]] 

[[ 2]
 [-6]]
[[ 2]
 [-6]]
n [[ 2]
 [-6]]
to tyle 


(2, 1)

Przykład 2

In [26]:
X = np.array([[2,-1,3],[3,1,0]])
Y = np.array([[2,1,-1],[0,-1,2],[3,2,0]])

Z= X@Y
print(Z)

[[13  9 -4]
 [ 6  2 -1]]


Wyznacznik macierzy
Macierz N = nxn *[macierz kwadratowa stopnia n]*


In [30]:
A = np.array([[2,4],[-1,3]])
X=np.linalg.det(A)
print(round(X))

10


In [31]:
np.trace(A)

5

Macierz jednostkowa

In [32]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Macierz odwrotna - macierz odwrotna macierzy A, to taka macierz B, przy których mnożeniu (BA albo A=B) wynik jest taki sam

In [37]:
np.set_printoptions(precision=4, suppress=True)
B=np.linalg.inv(A)
B

print(A@B)

[[1. 0.]
 [0. 1.]]


Transponowanie macierzy:

In [39]:
print(A.T)

[[ 2 -1]
 [ 4  3]]


rozwiązywanie układów równań

2x+4y=10

x-y=-1





In [42]:
A  = np.array ([[2,4],[1,- 1]])
B = np.array([[10],[-1]])
A_inv = np.linalg.inv(A)
X=A_inv@B
print(X)

[[1.]
 [2.]]
